package ar.com.leandroamarillo.productfinder

import ar.com.leandroamarillo.productfinder.network.MeliApi
import org.junit.Test
import java.io.IOException
import java.lang.RuntimeException
import org.junit.Assert.*
import kotlin.random.Random

const val RUNS = 1000
const val MAX_WORDS = 5

class APIModelTest {
    @Test
    fun autoGeneratedModel_doesntCrash() {
        /*
        * The api model was generated using https://json2kt.com/.
        * Since this could've missed some cases this test mas made to find
        * those mapping errors.
        */

        val words = listOf(
            "Samsung",
            "Apple",
            "Televisor",
            "4K",
            "Android",
            "Mercado Pago",
            "Play",
            "Usado",
            "0km",
            "nintendo",
            "celular",
            "bicicleta",
            "asdfasdf",
            "silla",
            "QUINTA",
            "MOTO",
            "LIBROS",
            "plumbus"
        )

        val errors = mutableListOf<String>()

        for (i in 1..RUNS) {
            val searchTerm = words.shuffled().take(Random.nextInt(1,MAX_WORDS)).joinToString(separator = " ")
            try {
                MeliApi.meliApiService.getSearch(searchTerm).execute()
            } catch (error: RuntimeException) {
                //Model Failed
                errors.add(error.message ?: "No Message")
            } catch (error: IOException) {
                //Problem occurred talking to the server, maybe it's down.
            }

        }

        assertEquals(mutableListOf<String>(), errors)

        if (errors.size != 0) {
            errors.forEach { e -> println(e)  }
        }
    }
}